#!/bin/bash

SCRIPT=$(readlink -f $0)
SCRIPTPATH=`dirname ${SCRIPT}`

${SCRIPTPATH}/precheck

NAME="glib"
VERSION="2.43.4"

source ${SCRIPTPATH}/config

### FETCH ###
if [ ! -d "${SRCdir}" ] 
then
	cd ${CACHEdir}
	wget http://ftp.gnome.org/pub/gnome/sources/glib/2.43/${NAME}-${VERSION}.tar.xz
else
	echo "WARNING: ${NAME}-${VERSION} is already downloaded"
fi


### EXTRACT ###
if [ ! -d "./${SRCdir}" ]
then
	mkdir "${SRCdir}"
	unxz "./${NAME}-${VERSION}.tar.xz" &>> ${LOG}
	tar -xf "./${NAME}-${VERSION}.tar" &>> ${LOG}
else
	echo "Warning: ${NAME}-${VERSION} is alread extracted"
fi


### COMPILE AND INSTALL ###
#export LIBFFI_CFLAGS=-I"${PREFIX}/include"
#export LIBFFI_LIBS="-L${PREFIX}/lib -lffi"
cd ${SRCdir}
./configure --prefix=${PREFIX} &>> ${LOG}
make -j${THREAD_NUM} &>> ${LOG}
make install &>> ${LOG}


### LINK ###
source ${SCRIPTPATH}/link
