#!/bin/bash

SCRIPT=$(readlink -f $0)
SCRIPTPATH=`dirname ${SCRIPT}`

module purge
module load openmpi/1.8.3-ib

${SCRIPTPATH}/precheck

NAME="postgresql"
VERSION="9.1.15"

source ${SCRIPTPATH}/config


### FETCH ###
if [ ! -d "${SRCdir}" ] 
then
	cd ${CACHEdir}
	#wget https://ftp.postgresql.org/pub/source/v9.4.1/postgresql-9.4.1.tar.gz
	wget ftp://ftp.postgresql.org/pub/source/v9.1.15/postgresql-9.1.15.tar.gz
else
	echo "WARNING: ${NAME}-${VERSION} is already downloaded"
fi


### EXTRACT ###
if [ ! -d "./${SRCdir}" ]
then
	mkdir "${SRCdir}"
	#gunzip "./${NAME}-${VERSION}.tar.gz"
	tar -xzvf "./${NAME}-${VERSION}.tar"
else
	echo "Warning: ${NAME}-${VERSION} is already extracted"
fi


### COMPILE AND INSTALL ###
cd ${SRCdir}
./configure --prefix=${PREFIX}
make -j${THREAD_NUM}
make install

