#!/bin/bash

SCRIPT=$(readlink -f $0)
export SCRIPTPATH=`dirname ${SCRIPT}`

${SCRIPTPATH}/precheck

export NAME="libpqxx"
MAJOR="4"
MINOR="0"
REVISION="1"
export VERSION="$MAJOR.$MINOR.$REVISION" 

source ${SCRIPTPATH}/config


### FETCH ###
if [ ! -d "${SRCdir}" ] 
then
	cd ${CACHEdir}
	wget "ftp://pqxx.org/software/libpqxx/${NAME}-${VERSION}.tar.gz"
else
	echo "WARNING: ${NAME}-${VERSION} is already downloaded"
fi


### EXTRACT ###
if [ ! -d "./${SRCdir}" ]
then 
	mkdir "${SRCdir}"
	tar -vzxf "./${NAME}-${VERSION}.tar.gz"
else
	echo "Warning: ${NAME}-${VERSION} is alread extracted"
fi


### COMPILE AND INSTALL ###
cd ${SRCdir}
./configure --prefix=${PREFIX} --with-pic=yes
make -j${THREAD_NUM}
make install


### LINK ###
source ${SCRIPTPATH}/link

