#!/bin/bash

SCRIPT=$(readlink -f $0)
SCRIPTPATH=`dirname ${SCRIPT}`

module purge
module load openmpi/1.8.3-ib

${SCRIPTPATH}/precheck

NAME="postgresql"
#9.4.1
#9.1.15
MAJOR="9"
MINOR="1"
REVISION="15"
VERSION="$MAJOR.$MINOR.$REVISION"

source ${SCRIPTPATH}/config


### FETCH ###
if [ ! -d "${SRCdir}" ] 
then
	cd ${CACHEdir}
	wget ftp://ftp.postgresql.org/pub/source/v$VERSION/$NAME-$VERSION.tar.gz
else
	echo "WARNING: ${NAME}-${VERSION} is already downloaded"
fi


### EXTRACT ###
if [ ! -d "./${SRCdir}" ]
then
	mkdir "${SRCdir}"
	tar -vzxf "./${NAME}-${VERSION}.tar.gz"
else
	echo "Warning: ${NAME}-${VERSION} is already extracted"
fi


### COMPILE AND INSTALL ###
cd ${SRCdir}
./configure --prefix=${PREFIX}
make -j${THREAD_NUM}
make install

