#!/bin/bash

SCRIPT=$(readlink -f $0)
export SCRIPTPATH=`dirname ${SCRIPT}`

${SCRIPTPATH}/precheck

export NAME="mosh"
export MAJOR="1"
export MINOR="2"
export REVISION="4"
export VERSION="$MAJOR.$MINOR.$REVISION"

source ${SCRIPTPATH}/config


### FETCH ###
if [ ! -d "${SRCdir}" ] 
then
	cd ${CACHEdir}
	#git clone https://github.com/keithw/mosh
	wget --no-check-certificate https://mosh.mit.edu/${NAME}-${VERSION}.tar.gz 
else
	echo "WARNING: ${NAME}-${VERSION} is already downloaded"
fi


## EXTRACT ###
if [ ! -d "./${SRCdir}" ]
then 
	mkdir "${SRCdir}"
	tar -xzvf "./${NAME}-${VERSION}.tar.gz"
else
	echo "Warning: ${NAME}-${VERSION} is alread extracted"
fi


### COMPILE AND INSTALL ###
#SRCdir="$CACHEdir/mosh"
cd ${SRCdir}
./autogen.sh
./configure --prefix=${PREFIX}
make -j${THREAD_NUM}
make install


### LINK ###
source ${SCRIPTPATH}/link

