#!/bin/bash

SCRIPT=$(readlink -f $0)
SCRIPTPATH=`dirname ${SCRIPT}`

${SCRIPTPATH}/precheck

NAME="cmake"
VERSION="3.2.0-rc1-Linux-x86_64"

source ${SCRIPTPATH}/config


### FETCH ###
if [ ! -d "${SRCdir}" ] 
then
	cd ${CACHEdir}
	#wget http://www.cmake.org/files/v3.2/cmake-3.2.0-rc1-linux-x86_64.tar.gz
	wget http://www.cmake.org/files/v3.2/${NAME}-${VERSION}.tar.gz
else
	echo "WARNING: ${NAME} is already downloaded"
fi


### EXTRACT ###
if [ ! -d "./${SRCdir}" ]
then
	mkdir "${SRCdir}"
	gunzip -f "./${NAME}-${VERSION}.tar.gz" &>> ${LOG}
	tar -xf "./${NAME}-${VERSION}.tar" &>> ${LOG}
else
	echo "Warning: ${NAME}-${VERSION} is alread extracted"
fi


### COMPILE AND INSTALL ###
cd ${CACHEdir}
mv ${NAME}-${VERSION} ${PREFIX}


### LINK ###
source ${SCRIPTPATH}/link
