#!/bin/bash

SCRIPT=$(readlink -f $0)
SCRIPTPATH=`dirname ${SCRIPT}`

${SCRIPTPATH}/precheck

module purge

NAME="glib"
MAJOR="2"
MINOR="48"
REVISION="0"
VERSION="$MAJOR.$MINOR.$REVISION"

source ${SCRIPTPATH}/config

cd $CACHEdir
FILE="${NAME}-${VERSION}.tar.xz"

### FETCH ###
if [ ! -f "${FILE}" ] 
then
	wget "http://ftp.gnome.org/pub/GNOME/sources/glib/${MAJOR}.${MINOR}/${FILE}"
else
	echo "WARNING: ${FILE} is already downloaded"
fi

### EXTRACT ###
if [ ! -d "./${SRCdir}" ]
then
	tar -xJf "${FILE}"
fi

### COMPILE AND INSTALL ###
cd ${SRCdir}
./configure --prefix=${PREFIX}
make -j16
make install
