#!/bin/bash

SCRIPT=$(readlink -f $0)
export SCRIPTPATH=`dirname ${SCRIPT}`

${SCRIPTPATH}/precheck

export NAME="swig"
export VERSION="3.0.5"

source ${SCRIPTPATH}/config


### FETCH ###
if [ ! -d "${SRCdir}" ] 
then
	cd ${CACHEdir}
	wget http://garr.dl.sourceforge.net/project/swig/swig/swig-3.0.5/${NAME}-${VERSION}.tar.gz
else
	echo "WARNING: ${NAME}-${VERSION} is already downloaded"
fi


### EXTRACT ###
if [ ! -d "./${SRCdir}" ]
then 
	mkdir "${SRCdir}"
	gunzip "./${NAME}-${VERSION}.tar.gz" &>> ${LOG}
	tar -xvf "./${NAME}-${VERSION}.tar" &>> ${LOG}
else
	echo "Warning: ${NAME}-${VERSION} is alread extracted"
fi


### COMPILE AND INSTALL ###
cd ${SRCdir}
./configure --prefix=${PREFIX}
make -j${THREAD_NUM} &>> ${LOG}
make install &>> ${LOG}


### LINK ###
source ${SCRIPTPATH}/link

