#!/bin/bash

SCRIPT=$(readlink -f $0)
export SCRIPTPATH=`dirname ${SCRIPT}`

${SCRIPTPATH}/precheck

export NAME="R"
export VERSION="3.1.2"

source ${SCRIPTPATH}/config


### FETCH ###
if [ ! -d "${SRCdir}" ] 
then
	cd ${CACHEdir}
	wget http://mirrors.softliste.de/cran/src/base/R-3/${NAME}-${VERSION}.tar.gz
else
	echo "WARNING: ${NAME}-${VERSION} is already downloaded"
fi


### EXTRACT ###
if [ ! -d "./${SRCdir}" ]
then 
	mkdir "${SRCdir}"
	gunzip "./${NAME}-${VERSION}.tar.gz" &>> ${LOG}
	tar -xvf "./${NAME}-${VERSION}.tar" &>> ${LOG}
else
	echo "Warning: ${NAME}-${VERSION} is alread extracted"
fi


### COMPILE AND INSTALL ###
cd ${SRCdir}
./configure --prefix=${PREFIX} --enable-R-shlib --enable-R-static-lib
make -j${THREAD_NUM} &>> ${LOG}
make install &>> ${LOG}


### LINK ###
source ${SCRIPTPATH}/link

