#!/bin/bash

SCRIPT=$(readlink -f $0)
export SCRIPTPATH=`dirname ${SCRIPT}`

${SCRIPTPATH}/precheck

export NAME="mosh"
export VERSION="1.2.4"

source ${SCRIPTPATH}/config


### FETCH ###
if [ ! -d "${SRCdir}" ] 
then
	cd ${CACHEdir}
	git clone https://github.com/keithw/mosh
	#wget --no-check-certificate https://mosh.mit.edu/${NAME}-${VERSION}.tar.gz 
else
	echo "WARNING: ${NAME}-${VERSION} is already downloaded"
fi


### EXTRACT ###
#if [ ! -d "./${SRCdir}" ]
#then 
	#mkdir "${SRCdir}"
	#gunzip "./${NAME}-${VERSION}.tar.gz" &>> ${LOG}
	#tar -xvf "./${NAME}-${VERSION}.tar" &>> ${LOG}
#else
	#echo "Warning: ${NAME}-${VERSION} is alread extracted"
#fi


### COMPILE AND INSTALL ###
SRCdir="$CACHEdir/mosh"
cd ${SRCdir}
./autogen.sh
./configure --prefix=${PREFIX}
make -j${THREAD_NUM} &>> ${LOG}
make install &>> ${LOG}


### LINK ###
source ${SCRIPTPATH}/link

