#!/bin/bash

SCRIPT=$(readlink -f $0)
export SCRIPTPATH=`dirname ${SCRIPT}`

${SCRIPTPATH}/precheck

export NAME="pcre"
MAJOR="8"
MINOR="35"
#REVISION="12"
#export VERSION="3.0.5"
export VERSION="$MAJOR.$MINOR"

source ${SCRIPTPATH}/config


### FETCH ###
if [ ! -d "${SRCdir}" ] 
then
	cd ${CACHEdir}

	wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/$NAME-$VERSION.tar.gz
else
	echo "WARNING: ${NAME}-${VERSION} is already downloaded"
fi


### EXTRACT ###
if [ ! -d "./${SRCdir}" ]
then 
	mkdir "${SRCdir}"
	tar -xzvf "./${NAME}-${VERSION}.tar.gz"
else
	echo "Warning: ${NAME}-${VERSION} is alread extracted"
fi


### COMPILE AND INSTALL ###
cd ${SRCdir}
./configure --prefix=${PREFIX}
make -j${THREAD_NUM}
make install


### LINK ###
source ${SCRIPTPATH}/link

