#!/bin/bash

SCRIPT=$(readlink -f $0)
SCRIPTPATH=`dirname ${SCRIPT}`

${SCRIPTPATH}/precheck

NAME="cmake"
MAJOR="3"
MINOR="2"
REVISION="0-rc1-Linux-x86_64"
VERSION="$MAJOR.$MINOR.$REVISION"
#VERSION="3.2.0-rc1-Linux-x86_64"

source ${SCRIPTPATH}/config


### FETCH ###
if [ ! -d "${SRCdir}" ] 
then
	cd ${CACHEdir}
	wget http://www.cmake.org/files/v3.2/${NAME}-${VERSION}.tar.gz
else
	echo "WARNING: ${NAME} is already downloaded"
fi


### EXTRACT ###
if [ ! -d "./${SRCdir}" ]
then
	mkdir "${SRCdir}"
	tar -xzvf "./${NAME}-${VERSION}.tar.gz"
else
	echo "Warning: ${NAME}-${VERSION} is alread extracted"
fi


### COMPILE AND INSTALL ###
cd ${CACHEdir}
mv ${NAME}-${VERSION} ${PREFIX}


### LINK ###
source ${SCRIPTPATH}/link
